### ISSUE TITLE
/api/v1/auth not in swagger

### ISSUE THREAD

**Issue by jinnatar** [lxc-webpanel/lxc-rest#3]
I'm totally new to swagger but the issue I had with some of the calls, for example /api/v1/lxc/containers is indeed due to not authenticating. I assumed the swagger is self-contained but it doesn't include the auth API, so cannot fully play with the api there without doing a manual curl call myself.

If it's possible, could the auth API be added to the swagger? Would help a lot in playing.

**Comment by ElieDeloumeau** [comment]
Yes it's in my todo list but /api/v1/auth isn't a flask-restplus endpoint, i probably need to rewrite this part

**Comment by ElieDeloumeau** [comment]
So, I will use *Flask JWT Extended*
